### ISSUE TITLE
Semver development releases

### ISSUE THREAD

**Issue by matt035343** [SneaksAndData/github-actions#10]
I would like to enable development releases in our semver GH action. The development release does not bump major, minor or patch but appends the version with a development version, example: `1.2.3-dev4` or `1.2.3-4-87wud21`. This feature should have a on/off switch.

In this repo: https://github.com/SneaksAndData/generic-mip, I would like a development release every time a commit is pushed to a PR. But this should not bump major, minor or patch.
This is because this framework is work-in-progress, and I don't want to make a proper release every time I want to test something out in another repo that depends on this one

**Comment by s-vitaliy** [comment]
Create something like altantis: comment to create a release
