### ISSUE TITLE
`poetry export` command deprecation

### ISSUE THREAD

**Issue by george-zubrienko** [SneaksAndData/github-actions#37]
We are supposed to use this https://github.com/python-poetry/poetry-plugin-export instead of `poetry export` command which will be removed next year I think. We should update template repos and all python repos to use this approach.

**Comment by s-vitaliy** [comment]
Solution should also fix #39

**Comment by george-zubrienko** [comment]
Poetry 1.5 removed `poetry export`, so we should:
- pin default poetry version to pre-1.5
- update repos using `poetry export` command and the template so they can work again.
